default_environment: cloud
environments:
    local:
        connections:
            duckdb:
                - name: "gharchive"
                  path: "gharchive.duckdb"

    cloud:
        connections:
            google_cloud_platform:
                - name: "gharchive_bq"
                  project_id: "gharchive-491810"
                  location: "US"
                  use_application_default_credentials: true
