name: gharchive-daily
schedule: "0 2 * * *"
start_date: "2026-03-01"
catchup: false

default_connections:
    duckdb: "gharchive"
    google_cloud_platform: "gharchive_bq"

default:
    type: duckdb.sql

variables:
    storage_mode:
        type: string
        default: "local"

    lookback_days:
        type: integer
        default: 7

    cloud_start_date:
        type: string
        default: "2026-03-23"
